# Generated by Django 5.1.3 on 2024-11-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankloan',
            fields=[
                ('Loan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Cust_id', models.IntegerField(max_length=50)),
                ('Cust_name', models.CharField(max_length=100)),
                ('Loan_amt', models.IntegerField()),
                ('Mail_id', models.EmailField(max_length=254)),
            ],
        ),
    ]
